#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.
# @see https://github.blog/2015-06-30-scripts-to-rule-them-all/

set -e

cd "$(dirname "$0")/.."

script/bootstrap

# Set up DB here
#echo "==> Setting up DB..."

# Set up env here here
#echo "==> Setting up env..."

echo "==> Repo is now ready to go!"
